#=============================================================================
# Advanced CPU architecture and Hardware Accelerators Lab 361-1-4693 BGU
# Compile every source of the RV32IM MCU into the "work" library.
#
# Run from this directory:    do compile.do
#=============================================================================
# Run this from SIM/RV32IMscMCU - the paths below are relative to it.
#
# Deliberately NOT [file normalize]d: if you reach the project through an
# ASCII directory junction (see the note at the bottom of this file),
# normalizing would resolve it back to the real path and ModelSim cannot
# open a path containing non-ASCII characters.
set DUT  ../../DUT/RV32IMscMCU
set TB   ../../TB/RV32IMscMCU
set PLLD ../../QUARTUS

# Drop any loaded simulation first, otherwise the work library stays locked.
# "file delete" rather than "vdel -all": vdel prints "Error 133: Unable to
# remove directory" straight to the transcript when the library is in use,
# and being its own output, catch cannot suppress it. Either way a stale
# library is harmless - vlib and vcom below just overwrite it.
catch {quit -sim}
catch {file delete -force work}
vlib work
vmap work work

# Order matters: packages first, then leaf modules, then the core, then the TBs
foreach f [list \
	$DUT/cond_compilation_package.vhd \
	$DUT/clk_config_package.vhd       \
	$DUT/const_package.vhd            \
	$DUT/aux_package.vhd              \
	$DUT/MULT.vhd                     \
	$DUT/SUBTRACTOR.vhd               \
	$DUT/DIV.vhd                      \
	$DUT/CDC_SYNC.vhd                 \
	$DUT/DIV_ACCEL.vhd                \
	$DUT/BidirPin.vhd                 \
	$DUT/SevenSegmentEncoder.vhd      \
	$DUT/GPIO_AddressDecoder.vhd      \
	$DUT/GPIO_LEDR_Interface.vhd      \
	$DUT/GPIO_SW_Interface.vhd        \
	$DUT/GPIO_HEX_Pair_Interface.vhd  \
	$DUT/CONTROL.VHD                  \
	$DUT/IDECODE.VHD                  \
	$DUT/IFETCH.VHD                   \
	$DUT/EXECUTE.VHD                  \
	$DUT/DMEMORY.VHD                  \
	$DUT/RV32I_CORE.vhd               \
	$DUT/MCU.vhd                      \
	$TB/tb_RV32I.vhd                  \
	$TB/tb_divider.vhd                \
	$TB/tb_cdc_sync.vhd               \
	$TB/tb_div_accel.vhd              \
	$TB/tb_SevenSegmentEncoder.vhd    \
	$TB/tb_GPIO_AddressDecoder.vhd    \
	$TB/tb_GPIO_LEDR_Interface.vhd    \
	$TB/tb_GPIO_SW_Interface.vhd      \
	$TB/tb_GPIO_HEX_Pair_Interface.vhd ] {
	echo "vcom $f"
	if {[catch {vcom -2008 -quiet $f} msg]} {
		echo "COMPILE FAILED: $f"
		echo $msg
		return
	}
}
#-----------------------------------------------------------------------------
# PLL simulation models - OPTIONAL.
#
# Only needed to simulate with MODELSIM = 0, i.e. the real PLL IP. The
# MODELSIM = 1 path builds its clocks behaviourally and never binds these, so
# a failure here is reported and stepped over rather than being fatal: the
# benchmark and the timer testbenches still run either way.
#
# altera_lnsim ships precompiled with ModelSim, so the libraries do not have
# to be built from Quartus sources. MODEL_TECH points at the simulator's bin
# directory, which keeps this working if ModelSim is installed elsewhere.
#-----------------------------------------------------------------------------
quietly set PLL_SIM_OK 1
if {[catch {vmap altera_lnsim "$::env(MODEL_TECH)/../altera/vhdl/altera_lnsim"} msg]} {
	echo "NOTE: altera_lnsim not found - PLL models skipped ($msg)"
	quietly set PLL_SIM_OK 0
}
if {$PLL_SIM_OK} {
	foreach p {PLL_MCLK PLL_DIVCLK PLL_SMCLK} {
		# the .vho defines <name>_pll_0, the wrapper instantiates it, so the
		# submodule has to be analysed first
		foreach f [list $PLLD/$p/simulation/submodules/${p}_pll_0.vho \
		                $PLLD/$p/simulation/$p.vhd] {
			if {![file exists $f]} {
				echo "NOTE: $f missing - run QUARTUS\\gen_plls.bat to regenerate"
				quietly set PLL_SIM_OK 0
				break
			}
			if {[catch {vcom -quiet $f} msg]} {
				echo "NOTE: PLL model failed to compile: $f"
				echo $msg
				quietly set PLL_SIM_OK 0
				break
			}
		}
		if {!$PLL_SIM_OK} { break }
	}
}

echo "-------------------------------------------------"
echo " compile OK"
if {$PLL_SIM_OK} {
	echo " PLL models compiled - MODELSIM=0 can be simulated too"
} else {
	echo " PLL models NOT compiled - use MODELSIM=1 (the default in the"
	echo " run scripts). Only the FPGA clock path is unavailable."
}
echo "-------------------------------------------------"

# NOTE: the clocks come from three altera_pll cores in QUARTUS/, one per
# clock, generated by QUARTUS/gen_plls.tcl. They are NOT the ALTPLL that came
# with the project - that is a Cyclone II megafunction and the Cyclone V of
# the DE10-Standard does not support it. Simulation normally bypasses the IP
# with MODELSIM=1; see the header of MCU.vhd.
#
# NOTE: ModelSim 20.1 cannot open a path containing non-ASCII characters,
# and the project lives under a Hebrew directory name. Reach it through an
# ASCII directory junction instead (one-off, no admin rights, no copying):
#
#   mklink /J C:\Users\oripa\rv32im "C:\Users\oripa\Documents\<hebrew>\RISC-V MCU Project"
#
# then work from C:\Users\oripa\rv32im\SIM\RV32IMscMCU. Remove it later with
# "rmdir C:\Users\oripa\rv32im", which deletes only the link.
