-- PLL_MCLK.vhd

-- Generated using ACDS version 21.1 842

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity PLL_MCLK is
	port (
		outclk_0_clk : out std_logic;        -- outclk_0.clk
		refclk_clk   : in  std_logic := '0'; --   refclk.clk
		rst_reset    : in  std_logic := '0'  --      rst.reset
	);
end entity PLL_MCLK;

architecture rtl of PLL_MCLK is
	component PLL_MCLK_pll_0 is
		port (
			refclk   : in  std_logic := 'X'; -- clk
			rst      : in  std_logic := 'X'; -- reset
			outclk_0 : out std_logic;        -- clk
			locked   : out std_logic         -- export
		);
	end component PLL_MCLK_pll_0;

begin

	pll_0 : component PLL_MCLK_pll_0
		port map (
			refclk   => refclk_clk,   --  refclk.clk
			rst      => rst_reset,    --   reset.reset
			outclk_0 => outclk_0_clk, -- outclk0.clk
			locked   => open          -- (terminated)
		);

end architecture rtl; -- of PLL_MCLK
